name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@AndMak1989'
          cache: 'npm'
      - run: npm install
      - run: npm run build -- --prod
#      - run: npm run test --watch=false
      - uses: JS-DevTools/npm-publish@v1
        with:
           token: ${{ secrets.NPM_AUTH_TOKEN }}
