name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
          with:
            node-version: 16.13.1
      - name: npm dependencies
          run: npm install
      - name: Build
          run: npm run build -- --prod
      - name: Publish
          run: npm run publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
